# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-feed]

# Jekyll feed settings
title:		     "Lagrange Home"
description: 	     "This blog is everything about Jekyll Theme Lagrange" 
url:		     "https://robqiao.github.io"
#baseurl:	     "/Lagrange"
auther:		     "LeNPaul"

