# Site Settings
url:		     "https://robqiao.github.io/Lagrange/"

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate]
